# Generated by Django 6.1.1 on 2026-09-30 00:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Categoría')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Personaje')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Personaje',
                'verbose_name_plural': 'Personajes',
                'db_table': 'personaje',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20, verbose_name='Código SKU')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Producto')),
                ('descripcion', models.CharField(max_length=250, verbose_name='Descripción')),
                ('tamano', models.CharField(choices=[('p', 'Pequeño (Llavero)'), ('m', 'Mediano (Peluche normal)'), ('g', 'Grande (Cojín)')], default='m', max_length=1)),
                ('precio', models.PositiveIntegerField(default=10000, verbose_name='Precio')),
                ('fecha_lanzamiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Lanzamiento')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='primeraApp.categoria')),
                ('personaje', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primeraApp.personaje')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['personaje', 'nombre'],
            },
        ),
    ]
